name: Test And Build

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

    workflow_dispatch:

jobs:

    test_and_build:

        runs-on: ubuntu-latest
        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b 

            - name: Set up Python
              run: uv python install

            - name: Check Linting (Quality Code)
              run: uv ruff check 

            - name: Test
              run: uv run pytest -vv

