name: Test And Build

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

    workflow_dispatch:

jobs:

    test_and_build:

        defaults:
          run:
            working-directory: src

        runs-on: ubuntu-latest
        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version-file: "pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b 

            - name: Test
              run: |
                pwd
                uv run pytest -v

